### ISSUE TITLE
Common Navigation Header

### ISSUE THREAD

**Issue by anitgandhi** [ieee-uiuc/ieee.illinois.edu-old#1]
The HTML and CSS for the navbar that will show up on all pages.
Link to: 
- IEEE UIUC Logo --> /
- About (with dropdown) --> /about
  - About IEEE UIUC --> /about/about-us
  - Executive Board --> /about/exec-board
  - Committees --> /about/committees
  - Contact Us --> /about/contact
- News (with dropdown) --> /news
  - Announce Archive --> /news/announce
  - Calendar --> /news/calendar
- Join --> /join
- Corporate Relation --> /corporate
- Awards --> /awards
- Spark --> spark.illinois.edu

**Comment by anselmoshim** [comment]
I have 2 feature requests:
1. A page to make payments (workshops, social events, corporate tech talks)
*payments.ieee.illinois.edu
This could be its own thing in the header?
2. Showcase page (past hackathons, projects, etc)
Might make sense to have this as a sub-page within About

**Comment by anitgandhi** [comment]
As of right now I'm purposely choosing not to do dropdown menus as they won't show up well on mobile in our current implementation. We can re-open the issue later on. 

This code should be included in every page at the end of the body element. 

``` html
<body>

...

<script src="/common/js/main.js"></script>

<!-- Load the header, and once that's done, call readyToGo to add in all the stuff from main.js -->
<script>
    $( "#menu" ).load( "/common/header.html", readyToGo);
    $( "#footer" ).load( "/common/footer.html" );
</script>

</body>
```
