### ISSUE TITLE
Create the CSS

### ISSUE THREAD

**Issue by anitgandhi** [ieee-uiuc/ieee.illinois.edu-old#13]
Now that a design is finalized, we need the CSS resources to match this design. 

Final designs are basically as follows: 

![image](https://raw.githubusercontent.com/ieee-uiuc/new/master/designs/Final/frontpage.png)
![image](https://raw.githubusercontent.com/ieee-uiuc/new/master/designs/Final/contentpage.png)

**Comment by anitgandhi** [comment]
Has anyone used CSS shapes enough to know how to make a custom CSS shape for the hill/wave that we have? Right now I'm working on making it in GIMP/PhotoShop with the pen tool. It gets the job done but as soon as we go responsive it might degrade fast

**Comment by anselmoshim** [comment]
Do you know if the template is a pre-made design from some website? Are we planning to custom make everything ourselves?

**Comment by anitgandhi** [comment]
Not sure what you're referring to? We're using PureCSS most likely for a lot of the CSS heavy lifting, and adding in whatever we need to match our theme.

**Comment by CalebAlbers** [comment]
If you are referring to us using a pre-made template, we aren't. Everything
was custom. Like Anit said, we will use PureCSS framework and go from there.

Anit -- I could export the shape of the hill as an SVG and then we can make
it into a CSS shape from there.

**Comment by anitgandhi** [comment]
All current/future CSS is/will be in /common/css/style.css
