### ISSUE TITLE
Bugs & Minor UI Improvements

### ISSUE THREAD

**Issue by CalebAlbers** [ieee-uiuc/ieee.illinois.edu-old#14]
This could probably be split into several smaller issues, however the following are small UI/UX issues that should be fixed.
- [x] Header/Nav scroll issues
  - [x] On desktop, the links should be vertically centered to the rest of the navbar
  - [x] The Nav bar behaves erratically when you switch between portrait and landscape mode on mobile browsers while the nav dropdown is open.
    ![screenshot_2015-04-09-15-38-47](https://cloud.githubusercontent.com/assets/7110138/7076883/3ec03b2e-ded2-11e4-9a21-11f1b09faa67.png)
    ![screenshot_2015-04-09-15-38-59](https://cloud.githubusercontent.com/assets/7110138/7076882/3e89fe4c-ded2-11e4-9ea0-c5d6648e9b6b.png)
  - [x] While in landscape mode on a phone, you cannot see the entire nav menu, however everything disappears if you happen to scroll.
    ![screenshot_2015-04-09-15-39-22](https://cloud.githubusercontent.com/assets/7110138/7076925/7cb04db6-ded2-11e4-868d-b64185bdf9aa.png)
  - [x] When changing height of navbar on scroll, add a jquery animation since CSS won't animate the height attribute
- [x] UI/UX Fixes
  - [x] The hill doesn't quite fill the entire width
  - [x] The "hamburger" icon should probably be moved down a bit on the page, similar to the placement of the IEEE@UIUC logo.
  - [x] Possibly make text smaller? Some pages have abnormally large font size.
    ![screenshot 04_09pm apr 09 2015](https://cloud.githubusercontent.com/assets/7110138/7076990/e8b6dc50-ded2-11e4-9a89-c05c9b70f1d2.png)
- [x] Footer issues
  - [x] Make the form on the footer fill out the width or at least be centered while displayed in mobile browsers
    ![screenshot_2015-04-09-15-36-42](https://cloud.githubusercontent.com/assets/7110138/7077005/0d3af0ca-ded3-11e4-9fe2-deb9ad31aa32.png)
  - [x] Fix the squeezed together layout for footer images.
  - [x] Add space between the links at the bottom the actual bottom of the footer.
  - [x] Add "text-decoration: none;" to the links so that they don't have any underlines.

**Comment by anselmoshim** [comment]
Shouldn't the footer icons be smaller and everything be centered? On the desktop version (Chrome), they are big and all side by side
![footer](https://cloud.githubusercontent.com/assets/7220078/7152177/fe78e4de-e2fb-11e4-933d-2f3edb2c04e4.PNG)

**Comment by actuallyaswin** [comment]
You guys should be making use of FontAwesome (
http://fortawesome.github.io/Font-Awesome/cheatsheet/) for all the social
icons. I'd reorganize the footer overall, imo.

Best regards,

_Aswin Sivaraman_
_UIUC Class of 2015 | ECE & CS_

**Comment by anitgandhi** [comment]
I did use FontAwesome briefly but I didn't want to include an entire stylesheet just for 3 logos (since IEEE and UIUC aren't on there obviously). I will, however, size them down, and bring them closer on desktop.

**Comment by anitgandhi** [comment]
@sivaram2 do you have a footer design idea in mind that would work better overall, in your opinion?

**Comment by anitgandhi** [comment]
@sivaram2 @anselmoshim The footer has been updated. Take a look when you get a chance. If it doesn't update make sure to do a hard refresh on your browser.

**Comment by anselmoshim** [comment]
It looks better. I was thinking of the icons, contact us, and copyright all on top of each other centered. But if you want that design, I guess it's fine.

In general, the scaling of everything on the website looks proportionally too big. 

Something like www.uber.com looks to be the right size.

**Comment by CalebAlbers** [comment]
@anselmoshim I would be inclined to agree regarding scaling. I believe I made note of the font size in the UI/UX issue, however I meant that more in terms of scaling like you mentioned.

**Comment by anitgandhi** [comment]
My only issue with that is that then it becomes a very tall footer. It looks fine on mobile but on desktop I personally think the footer becomes too tall. 

I can see what you're saying in sizing terms. In terms of proportionally too big, do you mean in terms of font sizes? Any places in particular where it seems more apparent than others?

**Comment by anselmoshim** [comment]
The font is good, I guess the size is the problem. When you looks at the "welcome to ieee branch" part, there is a lot of white space (it looks tall) (that paragraph also needs to be also stretched horizontally, it is currently centered towards the left).

**Comment by anitgandhi** [comment]
Paragraph is now stretched (not really sure why I didn't do that earlier...)
White space is hopefully fixed now

On a side note, I think we should think of some new wording for that and the /about/ page since we have a new website and new structure and all.

**Comment by CalebAlbers** [comment]
I played around with the footer a bit as far as organization goes.
![footeroption](https://cloud.githubusercontent.com/assets/7110138/7154108/33061c78-e318-11e4-8f9d-6e6108d712bb.png)

![footeroption2](https://cloud.githubusercontent.com/assets/7110138/7154111/37c95ec8-e318-11e4-8b0f-dbf35f233c4e.png)

I know this sounds weird, but do we really need the copyright and contact us links? Maybe shorten it to just "© 2015 IEEE @ UIUC" or something shorter. I don't know. I feel like we may be overcomplicating the footer a bit. We're at almost an uncanny valley - too much information to do a drop-dead simple footer, but not enough information to do a longer/fuller footer and still have it look filled.

**Comment by anselmoshim** [comment]
@anitgandhi The intro paragraph looks much better now. Also, what happened to the original background of the circuit diagram behind the twitter and POTW? I sorta liked it.

@CalebAlbers I really like those footers.

**Comment by anitgandhi** [comment]
@CalebAlbers I LOVE that first one, I'll see if I can't get that rolling right now. 

@anselmoshim I'm working on getting that back, it wasn't scaling well (especially on mobile), but I definitely want it!

**Comment by anitgandhi** [comment]
@CalebAlbers the only issue with that is how it would look on mobile...

**Comment by anitgandhi** [comment]
Alright I've added an alternate footer, however it's commented out until we can figure out how to make it look good on mobile.

**Comment by CalebAlbers** [comment]
@anitgandhi 
For the " While in landscape mode on a phone, you cannot see the entire nav menu, however everything disappears if you happen to scroll." sub-issue - what do you think about setting the body to static while function "toggleMenu" is active, then change the following EventListener

``` javascript
    document.getElementById('toggle').addEventListener('click', function (e) {
        toggleMenu();
    });
```

so that the menu can scroll down to the rest of the list items? We could use javascript's `.scroll` to see if the user has scrolled the height of our menu, then if they scroll down past that, have the menu disappear?

Just some UI/UX ideas. Thoughts?
