### ISSUE TITLE
Blog for News

### ISSUE THREAD

**Issue by anselmoshim** [ieee-uiuc/ieee.illinois.edu-old#15]
Just something to think about for before we release the website.

Would it be possible to have a blog style portion in the news tab where we can post things? Twitter is great, but I think for things like hackathons, CVD and projects fair needs more info.

We usually great a separate static page for bigger events. Should we continue that trend? Or consolidate large info pieces into a blog so it can be easily seen? (example of what we usually do: www.ieee.illinois.edu/hakentour)

We could even implement wordpress, blogger or tumblr to make things easier.

**Comment by anitgandhi** [comment]
this is already going to happen. its what the /news/ page will contain. and the news slider on the front page will contain a select few of the news items for a given week.

**Comment by anitgandhi** [comment]
also, I realize wordpress would make things easier but I'm really trying to move away from that. my implementation should make it easy for people to post things still.
