### ISSUE TITLE
Safari Display Issues

### ISSUE THREAD

**Issue by anitgandhi** [ieee-uiuc/ieee.illinois.edu-old#17]
On Safari desktop and on all iOS browsers, sometimes the content goes under the hill or splash. It's an issue with WebKit itself, and apparently Apple and/or WebKit maintainers don't want to fix it. It's not an issue in any other rendering engine.

See https://youtu.be/2Z2VDTIr9gI for a better idea of what I mean.

**Comment by CalebAlbers** [comment]
This issue appears to be fixed in recent versions of WebKit/Safari. User agents tested:
   *  Safari v9.0.1
   *  Safari iOS  v8.1 - iPhone
   *  Safari iOS  v8.1 - iPod Touch
   *  Safari iOS  v8.1 - iPad

Closing unless anybody else can replicate the bug

**Comment by CalebAlbers** [comment]
This issue appears to be fixed in recent versions of WebKit/Safari. User agents tested:

Safari v9.0.1
Safari iOS v8.1 - iPhone
Safari iOS v8.1 - iPod Touch
Safari iOS v8.1 - iPad
Closing #17 unless anybody else can replicate the bug

**Comment by anitgandhi** [comment]
This makes me very happy.
