### ISSUE TITLE
Finalize a design

### ISSUE THREAD

**Issue by anitgandhi** [ieee-uiuc/ieee.illinois.edu-old#3]
@sheelshah and @CalebAlbers will finalize a design soon, and we'll start making some CSS for it.

**Comment by anitgandhi** [comment]
Here's a link to the IEEE Visual Identity Guidelines: http://www.ieee.org/documents/ieee_quick_reference_guide.pdf

Personally I think the PMS 308 Blue and PMS 158 Orange could work well.

For font, either Verdana or Formata could work. The light versions work especially well.

**Comment by CalebAlbers** [comment]
The orange would definitely work well. Blue would be a little light, but may work. Thoughts, @sheelshah 
![palate](https://cloud.githubusercontent.com/assets/7110138/6321076/b407d60c-bab6-11e4-81e3-51b48e46f007.png)

BTW - I didn't mean to unassignSheel from the issue. I thought I was able to assign multiple people to tasks, but apparently not.

**Comment by anitgandhi** [comment]
Don't worry about the assignment, I was confused by it as well. I thought we could assign multiple people, but I guess not. I just put Sheel down first randomly.

I think the third column would work pretty well.

**Comment by sheelshah** [comment]
I'm good for that.

**Comment by anitgandhi** [comment]
Take a look at the links I just added [Here](https://github.com/ieee-uiuc/new/wiki/Notes-on-New-Website) with the PureCSS layouts we can use. It even takes care of the horizontal on desktop, vertical on mobile (with the "X" animation) layout for the navigation bar.
