### ISSUE TITLE
Common Footer

### ISSUE THREAD

**Issue by anitgandhi** [ieee-uiuc/ieee.illinois.edu-old#4]
Address
RSO Office in ECEB [1016 ECEB]
Links to Social Media
IEEE Logo - Link to national
UIUC Logo - Link to illinois.edu

**Comment by CalebAlbers** [comment]
@anitgandhi @sheelshah We discussed putting the Illinois logo in the footer as well, correct?

**Comment by sheelshah** [comment]
Yes that's correct. @anitgandhi @CalebAlbers. Are we still focusing on the same orange for the footer or the dark blue that @CalebAlbers and me had similar hex values for?

**Comment by CalebAlbers** [comment]
For reference, below are the colors that @sheelshah and I picked. The ones on the left are mine, and the ones on the right are Sheel's.

![colors](https://cloud.githubusercontent.com/assets/7110138/6319969/445622e2-ba97-11e4-8e0b-63b39395d96b.png)

Here it is with the IEEE blue in it (#006699 per http://www.ieee.org/documents/ieee_quick_reference_guide.pdf):

![colors-wieeeblue](https://cloud.githubusercontent.com/assets/7110138/6319978/a124afc0-ba97-11e4-80e0-73be391ff646.png)

**Comment by anitgandhi** [comment]
I would like to use that IEEE blue, but even I can see that the color choices that you guys had (and especially Caleb's orange) would work much better.

**Comment by CalebAlbers** [comment]
Well, we could always use the IEEE blue and then just use one of our choices in conjunction with it.

Along with that, the IEEE reference guide had some extended IEEE palate choices for blue and orange as well. It would also seem that they prefer if we use Verdana if possible. I don't think that is quite as important of a branding guideline as their logo stuff, however.

**Comment by anitgandhi** [comment]
I'm going to move this discussion to Issue #3 . Please go there.

**Comment by anitgandhi** [comment]
A few updates:

I think at this point it would make more sense if we just had the five logos (Facebook, Twitter, GitHub, UIUC, IEEE), and then one grid section for:
- Copyright
- Link to Contact Us
- Link to Site Map

We should make it a 2/3, 1/3 setup.

Also, note that the way .pure-u-md-1-6 (for example) works is by making the width 16.67% on desktop, but on mobile it becomes 100%. That's why right now the footer looks so tall on mobile.

Finally, try using the .pure-img class for the logos.

**Comment by anitgandhi** [comment]
This code should be included in every page at the end of the body element. 

``` html
<body>

...

<script src="/common/js/main.js"></script>

<!-- Load the header, and once that's done, call readyToGo to add in all the stuff from main.js -->
<script>
    $( "#menu" ).load( "/common/header.html", readyToGo);
    $( "#footer" ).load( "/common/footer.html" );
</script>

</body>
```
